config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'tops#index'
  resources :users do
    member do
      get :discard
    end
  end

  resources :services do
    collection do
      get :demand
      get :supply
      post :demand_create
      post :supply_create
    end
    resources :agreements, only: [:create, :update], module: 'services'
    resources :comments, only: [:create]
  end

  resources :cards

  resources :rooms do
    resources :messages, only: [:index, :create, :destroy]
    resources :evaluates, only: [:create], module: 'rooms'
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/service.rb
class Service < ApplicationRecord
  validates :title,  presence: true, length: { maximum: 30 }
  validates :detail, presence: true, length: { maximum: 1000 }
  validates :price,  presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 500, less_than_or_equal_to: 100000 }
  validates :time,   presence: true
  validates :work,   presence: true
  validates :user_id, presence: true
  validate :image_should_be_presence

  has_one_attached :image
  has_many   :comments, dependent: :destroy
  has_many   :rooms

  belongs_to :user
  belongs_to :area
  belongs_to :category

  enum work: { "demand": 0, "supply": 1 }
  enum progress: { "契約前": 0, "契約中": 1, "契約完了": 2 }

  scope :with_contract, ->(num) { where(work: num, progress: 0) }

  def image_should_be_presence
    errors.add(:image, :presence) unless image.attached?
  end

  def contract_status
    case self.progress
    when '契約前'
      self.progress = "契約中"
    when '契約中'
      self.progress = "契約完了"
    end
    self.save
  end
end

app/controllers/services/agreements_controller.rb
class Services::AgreementsController < ApplicationController
  before_action :have_card, only: [:create]
  def create
    @service = Service.find(params[:service_id])
    if @card && @service.work == 'supply'
      @customer = @card.set_customer
      Card.create_charge(@customer, @service)
    end
    @service.contract_status
    Room.create_room(@service, current_user)
    redirect_to current_user
    flash[:success] = "購入が完了しました。チャットルームを作成しましたので、連絡を取り合いましょう"
  end

  def update
    @service = Service.find(params[:service_id])
    @room = Room.find(params[:id])
    if @service && @room.activated == true
      @service.contract_status
      @room.change_activated
      redirect_to new_room_evaluate_path(@room)
    else
      redirect_to current_user
    end
  end

  private

  def have_card
    @card = Card.find_by(user_id: current_user.id)
    if @card == nil
      redirect_to current_user
      flash[:danger] = "カードを登録してください"
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :logged_in_user, only: [:demand, :demand_create, :supply, :supply_create, :show, :edit, :update, :destroy]
  before_action :correct_user, only: [:demand, :demand_create, :supply, :supply_create, :edit, :update, :destroy]
  before_action :find_service, only: [:show, :edit, :update, :destroy]

  def demand
    @service = Service.new
  end

  def demand_create
    @service = Service.new(service_params)
    if @service.save
      flash[:success] = "出品が完了しました"
      redirect_to @user
    else
      render :demand
    end
  end

  def supply
    @service = Service.new
  end

  def supply_create
    @service = Service.new(service_params)
    if @service.save
      flash[:success] = "出品が完了しました"
      redirect_to @user
    else
      render :supply
    end
  end

  def show
    @comment = Comment.new
    @comments = Comment.includes(:user).where(service_id: @service.id).recent(10)
  end

  def edit
  end

  def update
    if @service.update(service_params)
      redirect_to @service
      flash[:success] = "編集が完了しました"
    else
      render :edit
    end
  end

  def destroy
    if @service.user.id == @user.id
      @service.destroy
      redirect_to @user
      flash[:danger] = "削除しました"
    else
      render :show
    end
  end

  private

  def find_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:image, :title, :detail, :price, :time, :work, :area_id, :category_id).merge(user_id: current_user.id)
  end
end

app/views/services/_services_form.html.slim
= render 'parts/error_messages',model: f.object
.service_page_r_form
h4 イメージ画像
/ .service_page_r_form_image
/ 	= f.label :image
/ 		i.far.fa-file-image
/ 	= f.file_field :image
/ 	small 写真を１枚アップロードしてください。
.service_page_r_form_image
  = f.label :image , "v-bind:style" => "{ backgroundImage: 'url(' + uploadedImage + ')',backgroundSize: '100% 300px' }"
	i.far.fa-file-image
  = f.file_field :image , "v-on:change" => "onFileChange($event)"
.service_page_r_form
h4 タイトル
.service_page_r_form_title
	= f.text_field :title
	small 30文字以内
.service_page_r_form
h4 詳しい説明
.service_page_r_form_detail
	= f.text_area :detail
	small 1000文字以内
.service_page_r_form
h4 地域
.service_page_r_form_title
	= f.collection_select :area_id, Area.all,:id, :name, include_blank: '選択して下さい'
.service_page_r_form
h4 カテゴリー
.service_page_r_form_title
	= f.collection_select :category_id, Category.all,:id, :name, include_blank: '選択して下さい'
.service_page_r_form
h4 金額
.service_page_r_form_price
	= f.text_field :price
	small 500円〜100000円の間で入力してください
.service_page_r_form
h4 所要時間
.service_page_r_form_time
	= f.number_field :time,maxlength: 2,in: 0.5..24,step: 0.5
	small 0.5~24時間
- if request.path_info == demand_services_path
	.service_page_r_form
		.service_page_r_form_button
			= f.submit "サービスを要望する",class: "mypage_sec_edit_form_button_submit"
- elsif request.path_info == supply_services_path
	.service_page_r_form
		.service_page_r_form_button
			= f.submit "サービスを出品する",class: "mypage_sec_edit_form_button_submit"
- else
	.service_page_r_form
		.service_page_r_form_button
			= f.submit "保存する",class: "mypage_sec_edit_form_button_submit"
= javascript_pack_tag "file_preview"

app/views/services/demand.html.slim
= render partial: "parts/common_header"
.service
	.service_title
		h2 困りごとをだす
		p 悩みごとを出して誰かに頼んでみよう!
	.service_page.uk-grid.uk-flex-center
		.service_page_r.uk-width-3-5
			= form_for(@service,url: demand_create_services_path) do |f|
				= f.hidden_field :work,value: "demand"
				= render partial: 'services_form',locals: {f: f}
= render partial: 'parts/footer'

app/views/services/edit.html.slim
= render partial: "parts/common_header"
.service
	.service_title
		h2 編集する
		p 編集してより詳しく相手に伝えよう!
	.service_page.uk-grid.uk-flex-center
		.service_page_r.uk-width-3-5
			= form_for @service do |f|
				= render partial: 'services_form',locals: {f: f}
= render partial: 'parts/footer'

app/views/services/request.html.slim
= render partial: "parts/registration_header"
.service
	.service_title
		h2 なやみごとを出す
		p 悩みごとを出して誰かに頼んでみよう!
	.service_page.uk-grid.uk-flex-center
		.service_page_r.uk-width-3-5
			= form_for @service do |f|
				.service_page_r_form
					h4 イメージ画像
					.service_page_r_form_image
						= f.label :image
							i.far.fa-file-image
						= f.file_field :image
						small 写真を１枚アップロードしてください。
				/ .service_page_form
				/ 	h4 カテゴリー
				/ 	.service_page_form_image
				/ 		= f.file_field :image
				/ 		small 写真を１枚アップロードしてください。
				/ .service_page_form
				/ 	h4 地域
				/ 	.service_page_form_image
				/ 		= f.file_field :image
				/ 		small 写真を１枚アップロードしてください。
				.service_page_r_form
					h4 タイトル
					.service_page_r_form_title
						= f.text_field :title
						small 30文字以内
				.service_page_r_form
					h4 詳しい説明
					.service_page_r_form_detail
						= f.text_area :detail
						small 1000文字以内
				.service_page_r_form
					h4 金額
					.service_page_r_form_price
						= f.text_field :price
						small 500円〜100000円の間で入力してください
				.service_page_r_form
					h4 所要時間
					.service_page_r_form_time
						= f.number_field :time,maxlength: 2,in: 0.5..24,step: 0.5
						small 0.5~24時間
				.service_page_r_form
					.service_page_r_form_button
						= f.submit "サービスを要望する",class: "mypage_sec_edit_form_button_submit"
= render partial: 'parts/footer'

app/views/services/show.html.slim
= render partial: 'parts/common_header'
= render partial: "parts/flash"
.myservice_top
	.myservice_top_sec
		.myservice_top_sec_l.uk-width-2-3
			= image_tag(@service.image)
		.myservice_top_sec_r.uk-width-1-3
			h1
				= @service.title
			h2 ￥#{@service.price}
			.myservice_top_sec_r_buy
				- if @service.user == current_user 
					= link_to edit_service_path(@service),class: "myservice_top_sec_r_buy_button"
						i.fas.fa-edit
						span 編集する
					= link_to service_path(@service),method: :delete,class: "myservice_top_sec_r_buy_delete",data: { confirm: "削除してもよろしいですか？" }
						i.fas.fa-trash
						span 削除する
				- elsif @service.work == 'demand'
					= link_to service_agreements_path(@service),method: :post,class: "myservice_top_sec_r_buy_button",data: { confirm: "お手伝いしますか？" }
						i.fas.fa-hands-helping
						span 力になる
				- else
					= link_to service_agreements_path(@service),method: :post,class: "myservice_top_sec_r_buy_button",data: { confirm: "購入を確定しますか？" }
						i.fas.fa-shopping-cart
						span 購入する
.myservice_contents.uk-container.uk-width-1-1
	.myservice_contents_data.uk-grid.uk-flex-center
		.myservice_contents_data_sec.uk-width-2-3
			h2 詳細情報
			.myservice_contents_data_sec_wrap
				.myservice_contents_data_sec_wrap_title
					h5 カテゴリー
				.myservice_contents_data_sec_wrap_detail
					p
						= @service.category.name
			.myservice_contents_data_sec_wrap
				.myservice_contents_data_sec_wrap_title
					h5 地域
				.myservice_contents_data_sec_wrap_detail
					p
						= @service.area.name
			.myservice_contents_data_sec_wrap
				.myservice_contents_data_sec_wrap_title
					h5 所要時間
				.myservice_contents_data_sec_wrap_detail
					p
						= @service.time
			.myservice_contents_data_sec_wrap
				.myservice_contents_data_sec_wrap_title
					h5 詳細
				.myservice_contents_data_sec_wrap_detail
					p
						= simple_format @service.detail
		.myservice_contents_user.uk-width-1-3
			h5 出品者プロフィール
			.myservice_contents_user_sec
				= user_show_image(@service.user)
				.myservice_contents_user_sec_name
					= @service.user.nickname
				.myservice_contents_user_sec_intro
					h5 自己紹介
					= simple_format @service.user.introduction
		.myservice_contents_comment.uk-width-2-3
			h2 公開コメント
			.myservice_contents_comment_title
				h4 公開コメントを追加する
				= form_with model: [@service,@comment],local: true do |f|
					= f.text_area :detail
					small 50文字以内
					= f.submit "送信する",class: "replybutton"
					/ <button type="button" v-on:click="click(#{@service.id})">送信</button>
			.myservice_contents_comment_form
		.myservice_contents_comment.uk-width-2-3
			h2 コメント一覧	
			- @comments.each do |comment|
				article.uk-comment
					header.uk-comment-header.uk-grid-medium.uk-flex-middle[uk-grid]
						.uk-width-auto
							.uk-comment-avatar
								= user_show_image(comment.user)
						.uk-width-expand
							h4.uk-comment-title.uk-margin-remove
								= link_to comment.user.nickname,root_path,class: "uk-link-reset"
							ul.uk-comment-meta.uk-subnav.uk-subnav-divider.uk-margin-remove-top
								li
									p
										= simple_time(comment.created_at)
					.uk-comment-body
						p
							= comment.detail
= render partial: 'parts/footer'
= javascript_pack_tag "comment_create"

app/views/services/skills.html.slim
= render partial: "parts/registration_header"
.service
	.service_title
		h2 サービスを出品する
		p 自分の得意なこと、好きなことをサービスとして売り出そう!
	.service_page.uk-grid.uk-flex-center
		.service_page_r.uk-width-3-5
			= form_for @service do |f|
				.service_page_r_form
					h4 イメージ画像
					.service_page_r_form_image
						= f.label :image
							i.far.fa-file-image
						= f.file_field :image
						small 写真を１枚アップロードしてください。
				/ .service_page_form
				/ 	h4 カテゴリー
				/ 	.service_page_form_image
				/ 		= f.file_field :image
				/ 		small 写真を１枚アップロードしてください。
				/ .service_page_form
				/ 	h4 地域
				/ 	.service_page_form_image
				/ 		= f.file_field :image
				/ 		small 写真を１枚アップロードしてください。
				.service_page_r_form
					h4 タイトル
					.service_page_r_form_title
						= f.text_field :title
						small 30文字以内
				.service_page_r_form
					h4 詳しい説明
					.service_page_r_form_detail
						= f.text_area :detail
						small 1000文字以内
				.service_page_r_form
					h4 金額
					.service_page_r_form_price
						= f.text_field :price
						small 500円〜100000円の間で入力してください
				.service_page_r_form
					h4 所要時間
					.service_page_r_form_time
						= f.number_field :time,maxlength: 2,in: 0.5..24,step: 0.5
						small 0.5~24時間
				.service_page_r_form
					.service_page_r_form_button
						= f.submit "サービスを出品する",class: "mypage_sec_edit_form_button_submit"
= render partial: 'parts/footer'

app/views/services/supply.html.slim
= render partial: "parts/common_header"
.service
	.service_title
		h2 スキルを出品する
		p 自分の得意なこと、好きなことをサービスとして売り出そう!
	.service_page.uk-grid.uk-flex-center
		.service_page_r.uk-width-3-5
			= form_for(@service,url: supply_create_services_path) do |f|
				= f.hidden_field :work,value: "supply"
				= render partial: 'services_form',locals: {f: f}
= render partial: 'parts/footer'