config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'tops#index'
  resources :users do
    member do
      get :discard
    end
  end

  resources :services do
    collection do
      get :demand
      get :supply
      post :demand_create
      post :supply_create
    end
    resources :agreements, only: [:create, :update], module: 'services'
    resources :comments, only: [:create]
  end

  resources :cards

  resources :rooms do
    resources :messages, only: [:index, :create, :destroy]
    resources :evaluates, only: [:create], module: 'rooms'
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/views/parts/_card.html.slim
.uk-child-width-1-4(uk-grid)
	- model.each do |service|
		.uk-card.uk-card-default
			.uk-card-media-top
				.uk-card-media-top
					= image_tag(service.image)
				.uk-card-body
					- if logged_in?
						= link_to service.title,service_path(service),class: "uk-card-title"
					- else
						p.uk-card-body-title
							= service.title
					.uk-card-body-text
						.uk-card-body-text-area
							p 
								= service.area.name
						.uk-card-body-text-price
							p ￥ #{service.price}

app/views/parts/_common_header.html.slim
.uk-navbar-container(uk-navbar)
	.uk-navbar-center
		- if logged_in?
			.uk-navbar-center-left
				ul.uk-navbar-nav
					li
						= link_to "スキル",supply_services_path,class:"roll-button button_blue"
					li
						= link_to "お困り",demand_services_path,class:"roll-button button_purple"
					li 
						= link_to "クレジット",cards_path,class: "roll-button button_orange"
			= link_to "KotoKoto",root_path,class:"uk-navbar-item uk-logo"
			.uk-navbar-center-right
				ul.uk-navbar-nav
					li
						= link_to "ログアウト",logout_path,method: :delete,class:"roll-button button_red"
					li
						= link_to "マイページ",current_user,class: "roll-button button_yellow"
					li
						= link_to "編集",edit_user_path(current_user),class: "roll-button button_green button_edit"
		- else
			.uk-navbar-center-left
				ul.uk-navbar-nav
					li
						= link_to "ログイン",login_path,class:"roll-button button_yellow"
			= link_to "KotoKoto",root_path,class:"uk-navbar-item uk-logo"
			.uk-navbar-center-right
				ul.uk-navbar-nav
					li
						= link_to "新規登録",new_user_path,class: "roll-button button_green"

app/views/parts/_concept.html.slim
.concept
	h2 日々の小さな悩みを助け合おう。
	p 家事代行や周りには言えない愚痴を聞いてほしいなど、生活に関するサービスを受けたい人、提供したい人を繋げるアプリです。
	.concept__images
		.concept__images__section
			figure
				= image_tag("cafe_osyaberi_woman.png", alt: "カフェおしゃべり")
				figcaption 相談や周りには言えない愚痴など
		.concept__images__section
			figure
				= image_tag("english_speaking.png", alt: "英会話")
				figcaption 英語力をあげたい、英語のスキルを生かしたい。
		.concept__images__section
			figure
				= image_tag("game_trump_babanuki.png", alt: "ゲーム相手")
				figcaption 暇な時間を潰したいなど
.border-icon
	i.fab.fa-affiliatetheme

app/views/parts/_error_messages.html.slim
- if model.errors.any?
	#error_explanation
		.alert.alert-danger #{model.errors.count}つエラーがあります
		ul
			- model.errors.full_messages.each do |msg|
				li
					= msg

app/views/parts/_flash.html.slim
- flash.each do |key, value|
	<div class="uk-alert-#{key}" uk-alert>
		<a class="uk-alert-close" uk-close></a>
		p.flash_message #{value}
	</div>

app/views/parts/_footer.html.slim
.footer__copyright
	| copyright(c) All rights reserved KOKO

app/views/parts/_modal.html.slim
<div class="modal" v-if="modal">
	<div class="modal modal-overlay">
		<div class="modal-window">
			= form_with url: room_evaluates_path(room),local: true do |f|
				<button class="modal-default-button" @click="closeModal">✖️</button>
				<div class="modal-content">
					p 対応が良かったか
					.evaluate_form	
						= f.radio_button :support,1,id: "radio1"
						= f.label "1",for: "radio1",class: "radio_label"

						
						= f.radio_button :support,2,id: "radio2"
						= f.label "2",for: "radio2",class: "radio_label"

						
						= f.radio_button :support,3,id: "radio3"
						= f.label "3",for: "radio3",class: "radio_label"

						
						= f.radio_button :support,4,id: "radio4"
						= f.label "4",for: "radio4",class: "radio_label"

						
						= f.radio_button :support,5,id: "radio5"
						= f.label "5",for: "radio5",class: "radio_label"
					p 満足できましたか
					.evaluate_form
						= f.radio_button :satisfaction,1,id: "radio6"
						= f.label "1",for: "radio6",class: "radio_label"

						
						= f.radio_button :satisfaction,2,id: "radio7"
						= f.label "2",for: "radio7",class: "radio_label"

						
						= f.radio_button :satisfaction,3,id: "radio8"
						= f.label "3",for: "radio8",class: "radio_label"

						
						= f.radio_button :satisfaction,4,id: "radio9"
						= f.label "4",for: "radio9",class: "radio_label"

						
						= f.radio_button :satisfaction,5,id: "radio10"
						= f.label "5",for: "radio10",class: "radio_label"
					= f.submit "送信",class: "modal-submit"
				</div>
		</div>
	</div>
</div>

app/views/parts/_registration_header.html.slim
.uk-navbar-container(uk-navbar)
	.uk-navbar-center
		- if logged_in?
			.uk-navbar-center-left
				ul.uk-navbar-nav
					li
						= link_to "supply",supply_services_path,class:"roll-button button_blue"
					li
						= link_to "demand",demand_services_path,class:"roll-button button_purple"
			= link_to "LOGO",root_path,class:"uk-navbar-item uk-logo"
			.uk-navbar-center-right
				ul.uk-navbar-nav
					li
						= link_to "logout",logout_path,method: :delete,class:"roll-button button_red"
					li
						= link_to "mypage",current_user,class: "roll-button button_yellow"
					li
						= link_to "edit",edit_user_path(current_user),class: "roll-button button_green button_edit"
		- else
			.uk-navbar-center-left
				ul.uk-navbar-nav
					li
						= link_to "ログイン",login_path,class:"roll-button button_yellow"
			= link_to "LOGO",root_path,class:"uk-navbar-item uk-logo"
			.uk-navbar-center-right
				ul.uk-navbar-nav
					li
						= link_to "新規登録",new_user_path,class: "roll-button button_green"