config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'tops#index'
  resources :users do
    member do
      get :discard
    end
  end

  resources :services do
    collection do
      get :demand
      get :supply
      post :demand_create
      post :supply_create
    end
    resources :agreements, only: [:create, :update], module: 'services'
    resources :comments, only: [:create]
  end

  resources :cards

  resources :rooms do
    resources :messages, only: [:index, :create, :destroy]
    resources :evaluates, only: [:create], module: 'rooms'
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /([\w+\-.]+)@[a-z\d]+\.[a-z]{2,3}/i
  validates :name,                 presence: true, length: { maximum: 50 }
  validates :nickname,             presence: true, length: { maximum: 30 }
  validates :email,                presence: true, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :password,             presence: true, length: { minimum: 6 }, allow_nil: true
  validates :password_confirmation, presence: true, allow_nil: true
  validates :introduction, length: { maximum: 200 }

  has_secure_password # セキュアなパスワードを作成 password_digestカラム gem bcrypt
  has_one_attached :image # activeStorage
  has_many :services, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :cards,    dependent: :destroy
  has_many :room_users
  has_many :rooms,    through: :room_users
  has_many :messages, dependent: :destroy

  attr_accessor :remember_token, :activation_token, :reset_token, :support_point, :satisfaction_point

  before_save :downcase_email
  before_create :create_activation_digest

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # トークンを作成
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # remember_token&remember_digestを作成
  def remember
    self.remember_token = User.new_token # 新しいトークンを作る
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest") # send(:remember_digest)
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token) # digestとtokenを比較して同じかどうか
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # パスワードの再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def place_value(support, satisfaction)
    self.support_point = support.to_i
    self.satisfaction_point = satisfaction.to_i
  end

  def create_confidence_score
    self.score += (self.support_point + self.satisfaction_point) * 2
  end

  def create_point
    if 500 < score
      self.point += self.score * 5
    elsif 200 < self.score
      self.point += self.score * 4
    elsif 100 < self.score
      self.point += self.score * 3
    elsif 50 < self.score
      self.point += self.score * 2
    else
      self.point += self.score
    end
    self.save
  end

  private

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :discord]
  before_action :correct_user, only: [:show, :edit, :update, :discard, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(new_user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      # 有効化
      flash[:warning] = "メールをご確認して有効にしてください"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @demand_services = @user.services.with_contract(0)
    @supply_services = @user.services.with_contract(1)
    @rooms = @user.rooms.where(activated: true)
    @finish_rooms = @user.rooms.where(activated: false).recent(8)
  end

  def edit
  end

  def update
    if @user.update(edit_user_params)
      if @card = Card.find_by(user_id: @user.id)
        @customer = @card.set_customer
        @customer.email = @user.email
        @customer.save
      end
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to @user
    else
      render :edit
    end
  end

  def discard
  end

  def destroy
    log_out if logged_in?
    if @card = Card.find_by(user_id: @user.id)
      @customer = @card.set_customer
      @card.delete_payjp(@customer)
    end
    @user.destroy
    flash[:alert] = "退会しました"
    redirect_to root_path
  end

  private

  def new_user_params
    params.require(:user).permit(:name, :nickname, :email, :password, :password_confirmation)
  end

  def edit_user_params
    params.require(:user).permit(:name, :nickname, :email, :introduction, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_show_image(user)
    user.image.attached? ? image_tag(user.image) : image_tag("user_default.jpeg")
  end

  def display_score(user)
    user.score == nil ? 0 : user.score
  end
end

app/views/users/_before_contract.html.slim
- services.each do |service|
	article
		= user_show_image(current_user)
		.article_body
			.article_body_info
				p 
					= simple_time(service.created_at)
			.article_body_title
				= link_to "#{service.title}",service_path(service)
			.article_body_link
				= link_to "編集",edit_service_path(service),class: "article_body_link_edit"
				= link_to "削除",service_path(service),method: :delete,class: "article_body_link_delete",data: { confirm: "削除してもよろしいですか？" }

app/views/users/_finish_contract.html.slim
- rooms.each do |room|
	article
		= user_show_image(current_user)
		.article_body
			.article_body_info
				p 
					= simple_time(room.updated_at)
			.article_body_title
				p #{room.name}

app/views/users/_under_contract.html.slim
- rooms.each do |room|
	article
		= image_tag("room.jpeg")
		.article_body
			.article_body_info
				p 
					= simple_time(room.created_at)
			.article_body_title
				= link_to "#{room.name}のチャットルーム",room_messages_path(room)
		/ .article_fin
		/ 	- if room.rated_user != current_user.id
		/ 		= link_to "完了にする",service_agreement_path(room.find_service_id,room),method: :put
		<div class="article_fin">
			- if room.rated_user != current_user.id
				/ = link_to "完了にする",service_agreement_path(room.find_service_id,room),method: :put
				<a @click="openModal">完了する</a>
		</div>
	= render partial: "parts/modal", locals: {room: room}

app/views/users/_user_sidebar.html.slim
.mypage_sec_cat.uk-width-1-5
			.mypage_sec_cat_title
			ul
				li 
					= link_to "マイページ",current_user
					i.fas.fa-chevron-right
				li 
					= link_to "困りごとを出す",demand_services_path
					i.fas.fa-chevron-right
				li 
					= link_to "スキルを出品する",supply_services_path
					i.fas.fa-chevron-right
				li 
					= link_to "プロフィール編集",edit_user_path(current_user)
					i.fas.fa-chevron-right
				- if card_present?
					li 
						= link_to "支払い方法",cards_path
						i.fas.fa-chevron-right
				- else
					li 
						= link_to "支払い方法",new_card_path
						i.fas.fa-chevron-right
				li 
					= link_to "パスワード変更",new_password_reset_path
					i.fas.fa-chevron-right
				li 
					= link_to "ログアウト",logout_path,method: :delete
					i.fas.fa-chevron-right
				li 
					= link_to "退会申請",discard_user_path(current_user)
					i.fas.fa-chevron-right
				li 
					= link_to "テスト2",root_path
					i.fas.fa-chevron-right

app/views/users/discard.html.slim
= render partial: 'parts/common_header'
.discard
	.discard_wrap 
		h2 退会
		.discard_wrap_content
			h3 注意事項
			p 退会された場合はそれまでの結果や評価の履歴が削除されますので、ご了承ください。			
			= link_to "退会する",user_path(current_user),method: :delete,class: "discard_wrap_content_button",data: { confirm: "削除してもよろしいですか？" }
= render partial: 'parts/footer'

app/views/users/edit.html.slim
= render partial: 'parts/common_header'
.mypage.uk-container
	.mypage_sec.uk-grid.uk-flex-center
		= render partial: 'user_sidebar'
		.mypage_sec_edit.uk-width-4-5
			= user_show_image(current_user)
			= form_for @user do |f|
				= render 'parts/error_messages',model: f.object
				.mypage_sec_edit_form.uk-width-1-1
					.mypage_sec_edit_form_nickname.uk-width-1-2
						= f.label :ニックネーム
						= f.text_field :nickname
						small 30文字以内
					.mypage_sec_edit_form_image.uk-width-1-2
						= f.label :アイコン
						= f.file_field :image
				.mypage_sec_edit_form
					.mypage_sec_edit_form_name.uk-width-1-2
						= f.label :名前
						= f.text_field :name
					.mypage_sec_edit_form_email.uk-width-1-2
						= f.label :メールアドレス
						= f.email_field :email
				.mypage_sec_edit_form
					.mypage_sec_edit_form_introduction.uk-width-1-1
						= f.label :自己紹介
						= f.text_area :introduction
						small 200文字以内
				.mypage_sec_edit_form
					.mypage_sec_edit_form_button
						= f.submit "保存する",class: "mypage_sec_edit_form_button_submit"
= render partial: 'parts/footer'

app/views/users/new.html.slim
= render partial: 'parts/common_header'
.form_wrapper
	h2 新規会員登録
	.form_design
		= form_for @user do |f|
			= render 'parts/error_messages',model: f.object
			.field
				= f.label :name
				br
				=f.text_field :name
			.field
				= f.label :nickname
				br
				=f.text_field :nickname
			.field
				= f.label :email
				br
				= f.email_field :email, autofocus: true
			.field
				= f.label :password
				br
				= f.password_field :password
			.field
				= f.label :password_confirmation
				br
				= f.password_field :password_confirmation
			.actions
				= f.submit "新規登録",class: "button"
= render partial: 'parts/footer'

app/views/users/show.html.slim
= render partial: 'parts/common_header'
= render partial: "parts/flash"
.mypage.uk-container
	.mypage_sec.uk-grid.uk-flex-center
		= render partial: 'user_sidebar'
		.mypage_sec_r.uk-width-1-5
			h5 マイページ
			.mypage_sec_r_icon
				= user_show_image(current_user)
				p
					= current_user.nickname
			.mypage_sec_r_introduction
				h6 自己紹介
				p 
					= simple_format current_user.introduction
			.mypage_sec_r_edit
				= link_to edit_user_path(current_user) do
					i.far.fa-address-card
					| プロフィールを編集する
			.mypage_sec_r_point
				h6 所持ポイント
				p #{current_user.point}pt
		.mypage_sec_l.uk-width-3-5
			.mypage_sec_l_score
				h5 信頼スコア
				.mypage_sec_l_score_circle
					.mypage_sec_l_score_circle_data
						h5
							= display_score(current_user)
						p 現在のスコア
			.mypage_sec_l_tags
				ul.uk-child-width-expand[uk-tab]
					<li v-on:click="change('1')">
						= link_to "契約前(困りごと)"
					</li>
					<li v-on:click="change('2')">
						= link_to "契約前(スキル)"
					</li>
					<li v-on:click="change('3')">
						= link_to "契約中(チャット)"
					</li>
					<li v-on:click="change('4')">
						= link_to "契約完了"
					</li>
			<div class ="mypage_sec_l_tablelist" v-if="isActive === '1'" v-bind:class="{'show': isActive === '1'}">
				= render 'before_contract', services: @demand_services
			</div>
			<div class ="mypage_sec_l_tablelist" v-else-if="isActive === '2'" v-bind:class="{'show': isActive === '2'}">
				= render 'before_contract', services: @supply_services
			</div>
			<div class ="mypage_sec_l_tablelist" v-else-if="isActive === '3'" v-bind:class="{'show': isActive === '3'}">
				= render 'under_contract', rooms: @rooms
			</div>
			<div class ="mypage_sec_l_tablelist" v-else-if="isActive === '4'" v-bind:class="{'show': isActive === '4'}">
				= render 'finish_contract', rooms: @finish_rooms
			</div>
= render partial: 'parts/footer'
= javascript_pack_tag "hello_vue"