config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'tops#index'
  resources :users do
    member do
      get :discard
    end
  end

  resources :services do
    collection do
      get :demand
      get :supply
      post :demand_create
      post :supply_create
    end
    resources :agreements, only: [:create, :update], module: 'services'
    resources :comments, only: [:create]
  end

  resources :cards

  resources :rooms do
    resources :messages, only: [:index, :create, :destroy]
    resources :evaluates, only: [:create], module: 'rooms'
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  def self.create_charge(customer, service)
    Payjp.api_key = ENV["PAYJP_KEY"]
    Payjp::Charge.create(
      amount: service.price,
      customer: customer,
      currency: 'jpy'
    )
  end

  def self.create_customer(user, payjp_token)
    Payjp.api_key = ENV["PAYJP_KEY"]
    @customer = Payjp::Customer.create(
      email: user.email,
      card: payjp_token
    )
  end

  def set_customer
    Payjp.api_key = ENV["PAYJP_KEY"]
    Payjp::Customer.retrieve(self.customer_id)
  end

  def delete_payjp(customer)
    self.destroy
    customer.delete
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_payjp, only: [:index, :destroy]
  include CardsHelper

  def index
    @card_information = @customer.cards.retrieve(@card.card_id)
  end

  def new
  end

  def create
    @customer = Card.create_customer(current_user, @payjp_token = params['payjp-token'])
    @card = Card.new(user_id: current_user.id, customer_id: @customer.id, card_id: @customer.default_card)
    if @card.save
      redirect_to current_user
      flash[:success] = "カード情報を登録しました"
    else
      render :new
      flash[:danger] = "不正な情報です"
    end
  end

  def destroy
    if @card.delete_payjp(@customer)
      redirect_to user_path(current_user.id)
      flash[:danger] = "カード情報を削除しました"
    end
  end

  private

  def set_payjp
    @card = Card.find_by(user_id: current_user.id)
    @customer = @card.set_customer
  end
end

app/helpers/cards_helper.rb
module CardsHelper
  def expiration_date(card_infomation)
    "#{card_infomation.exp_month}/#{card_infomation.exp_year}"
  end

  def card_present?
    current_user.cards.present?
  end
end

app/views/cards/index.html.slim
= render partial: 'parts/common_header'
= render partial: "parts/flash"
.mypage.uk-container
	.mypage_sec.uk-grid.uk-flex-center
		= render partial: 'users/user_sidebar'
		.mypage_sec_show.uk-width-4-5
			h2 支払い方法
			.mypage_sec_show_inner
				.mypage_sec_show_inner_head
					i.fas.fa-credit-card
					span
						h3 クレジットカード情報
				= form_with url: card_path(@card), local: true, method: :delete,class: "mypage_sec_show_inner_cont" do |f|
					.mypage_sec_show_inner_cont_num
						h5 カード情報
						p
							= "*********#{@card_information.last4}"
					.mypage_sec_show_inner_cont_num
						h5 使用期限
						p
							= expiration_date(@card_information)
					.mypage_sec_show_inner_cont_num
						= f.submit "削除する"
= render partial: 'parts/footer'

app/views/cards/new.html.slim
= render partial: 'parts/common_header'
= render partial: "parts/flash"
.mypage.uk-container
	.mypage_sec.uk-grid.uk-flex-center
		= render partial: 'users/user_sidebar'
		.mypage_sec_card.uk-width-4-5
			.mypage_sec_card_form
				h2 お支払い情報登録
				= form_with url: cards_path,local: true do
					script.payjp-button(src="https://checkout.pay.jp/" data-key="pk_test_e246c413fbda648615274bd1" data-text="カード情報を入力する" data-submit-text="カード情報を登録する" type="text/javascript")
= render partial: 'parts/footer'